[book]
authors = ["Impl trait Members"]
language = "en"
multilingual = false
src = "."
title = "Impl trait initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/impl-trait"

[output.html.fold]
enable = true
level = 0
